config/routes.rb
Rails.application.routes.draw do

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
 class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def articles_params
    params.require(:article).permit(:title, :body)
  end

  def create
    @article = Article.new(articles_params)

    if @article.save
      redirect_to articles_path, :notice => "Your new article was created!"
    else
      render "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(articles_params)
      redirect_to articles_path, :notice => "Your article was updated!"
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path, :notice => "Your article was deleted!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>This is Edit</h1>

<%= form_for @article do |f| %>

<p>
  <%= f.label :title %>: <%= f.text_field :title %>
</p>

<p>
  <%= f.label :body %>: <%= f.text_area :body %>
</p>

<p>
  <%= f.submit "Edit Article" %>
</p>

<% end %>

app/views/articles/index.html.erb
<h1>This is Index</h1>

<% @articles.each do |article| %>
<p>
  <%= link_to article.title, article %>
</p>
<hr>
<% end %>

<p>
  <%= link_to "Add Article", new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>This is new Page</h1>

<%= form_for @article do |f| %>

<p>
  <%= f.label :title %>: <%= f.text_field :title %>
</p>

<p>
  <%= f.label :body %>: <%= f.text_area :body %>
</p>

<p>
  <%= f.submit "Add Article" %>
</p>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
  <%= @article.body %>
</p>
<p>
  <%= @article.created_at %>
</p>
<p>
  <%= link_to "Edit", edit_article_path(@article) %>
  <%= link_to "Delete", @article, :confirm => "Are you sure?", :method => :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, message| %>
  <%= content_tag :div, message, :id => "alert_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>